POST http://localhost:3000/v1/auth/register
content-Type: application/json

{
    "fullName": "Admin Star",
    "email": "abujaAdmin@gmail.com",
    "password": "12245"
}

###
POST http://localhost:3000/v1/auth/login
content-Type: application/json

{
    "email": "abujaAdmin@gmail.com",
    "password": "12245"
}


###
POST http://localhost:3000/v1/admin/quiz
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmFmNzU0NzY1NTI0MzlkNzM4OTU0NzQiLCJmdWxsTmFtZSI6IkFkbWluIFN0YXIiLCJlbWFpbCI6ImFidWphQWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzIyNzg0OTc2fQ.ahEzfXDsBYGDVnaUeXpEgtaghoC1dpqCUAmFE7QIBd4

{
    "questionNumber": "6",
    "question": "What is a baby lion called?",
    "optionA": "Baby lion",
    "optionB": "Cob",
    "optionC": "Lioness",
    "optionD": "Lion baby",
    "correctOption": "optionB"
}

###
GET http://localhost:3000/v1/admin/quiz/1/10
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmFmNzU0NzY1NTI0MzlkNzM4OTU0NzQiLCJmdWxsTmFtZSI6IkFkbWluIFN0YXIiLCJlbWFpbCI6ImFidWphQWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzIyNzg0OTc2fQ.ahEzfXDsBYGDVnaUeXpEgtaghoC1dpqCUAmFE7QIBd4

###
PUT http://localhost:3000/v1/admin/quiz/66afa533b1e62953e0fda9ac
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmFmNzU0NzY1NTI0MzlkNzM4OTU0NzQiLCJmdWxsTmFtZSI6IkFkbWluIFN0YXIiLCJlbWFpbCI6ImFidWphQWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzIyNzg0OTc2fQ.ahEzfXDsBYGDVnaUeXpEgtaghoC1dpqCUAmFE7QIBd4

{
    "questionNumber": "6",
    "question": "What is a baby lion called?",
    "optionA": "Baby lion",
    "optionB": "Cob",
    "optionC": "Lioness",
    "optionD": "Lion baby",
    "correctOption": "optionB"
}